GET /patent/token HTTP/1.1
Host: {{host}}
###

GET /patent/classification HTTP/1.1
Host: {{host}}

###
GET /patent/simple/search?ttl=5g HTTP/1.1
Host: {{host}}

###
GET /patent?ttl=5g HTTP/1.1
Host: {{host}}

###