###基于用户协同过滤
GET /recommend/userbase?openid=op_RswgYs5QX99bnqYNZtH0KJvrg&howMany=1 HTTP/1.1
Host: {{host}}

###基于物品协同过滤
GET /recommend/itembase?openid=op_RswgYs5QX99bnqYNZtH0KJvrg&patentId=70ba5ee0443fdac1ea4eff261307053adaa93fe0a49f59df496dc5ef5963d05a612b00c6c21e68ee77af97ccaf0b8fc5 HTTP/1.1
Host: {{host}}

###训练隐语义
GET /recommend/training HTTP/1.1
Host: {{host}}

###LFM
GET /recommend/latent?openid=op_RswgYs5QX99bnqYNZtH0KJvrg HTTP/1.1
Host: {{host}}

###

